### ISSUE TITLE
create wireframe of the app

### ISSUE THREAD

**Issue by zilahir** [zilahir/R0335-3003_5#2]
the wireframe should contain the 

- screens
- logical connection between screens (as navigation?)
- functional declarations (what functions should we implemented in the app)

**Comment by menno-lab** [comment]
Mockups for the login and register pages:

https://www.figma.com/file/I3bFTtKCdBcEcIS8ASt9Ek/Hoodbars?node-id=0%3A1

Mockups for loading screen, map view and focus view:

https://www.figma.com/file/I3bFTtKCdBcEcIS8ASt9Ek/Hoodbars

**Comment by menno-lab** [comment]
Functional declarations (hope I understood this correctly):

- Authentication flow (maybe also a social login like Facebook)
- Users need to be able to create new locations
- Rate existing locations
- Provide info on existing location (opening hours, price, address)
- All existing locations should have markers on the map view
